WRW_Website/WRW_Website/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    re_path(r'^', include('homepage.urls')),
    re_path(r'^projects/', include('projects.urls')),
    re_path(r'^projects/arcade/', include('arcade.urls')),
    re_path(r'^projects/surf/', include('surf.urls')),
    path('admin/', admin.site.urls),
]

WRW_Website/arcade/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'arcade'

urlpatterns = [
    re_path(r'^phishing$', views.phishing, name='phishing'),
    re_path(r'^$', views.arcade, name='index'),
]

WRW_Website/homepage/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^about', views.about, name='about'),
]

WRW_Website/projects/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'projects'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),

]

WRW_Website/surf/urls.py
from django.urls import path, re_path, include
from rest_framework import routers
from rest_framework import generics
from . import views


app_name = 'surf'
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'books', views.BookView)
router.register(r'authors', views.AuthorView)

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^landingpage', views.landingpage, name='landingpage'),
    re_path(r'^login', views.login, name='login'),
    re_path(r'^simple_animation', views.simpleAnimation, name='simpleAnimation'),
    # re_path(r'^api/', include('surf.api.urls')),
    re_path(r'^api/', include(router.urls), name='api'),




    # re_path(r'^api/$', views.BookListAPIView.as_view(), name='book-list'),
    # re_path(r'^api/(?P<pk>\d+)/', views.BookDetailAPIView.as_view(), name='book-detail'),
    # re_path(r'^api/author/$', views.AuthorListAPIView.as_view(), name='author-list'),
    # re_path(r'^api/author/(?P<pk>\d+)/', views.AuthorDetailAPIView.as_view(), name='author-detail'),

]

WRW_Website/arcade/models.py
from django.db import models

# Create your models here.

WRW_Website/homepage/models.py
from django.db import models

# Create your models here.

WRW_Website/projects/models.py
from django.db import models

# Create your models here.

WRW_Website/surf/models.py
from django.db import models


class Author(models.Model):
    firstName = models.CharField(max_length=64)
    lastName = models.CharField(max_length=64)

    def __str__(self):
        return "%s %s" % (self.firstName, self.lastName)

    def __unicode__(self):
        return "%s %s" % (self.firstName, self.lastName)



class Book(models.Model):
    title = models.CharField(max_length=128)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

WRW_Website/WRW_Website/views.py
from django.shortcuts import render, get_object_or_404

WRW_Website/arcade/views.py
from django.shortcuts import render


def arcade(request):
    return render(request, 'arcade/index.html')


def phishing(request):
    return render(request, 'arcade/phishing.html')

WRW_Website/homepage/views.py
from django.shortcuts import render, get_object_or_404


def index(request):
    return render(request, 'homepage/index.html')


def about(request):
    return render(request, 'homepage/about.html')

WRW_Website/projects/views.py
from django.shortcuts import render, get_object_or_404


def index(request):
    return render(request, 'projects/index.html')

WRW_Website/surf/views.py
from django.shortcuts import render
from rest_framework.generics import ListAPIView, RetrieveAPIView
from .models import Book, Author
from .serializers import BookSerializer, AuthorSerializer
from rest_framework.viewsets import ModelViewSet


class BookView(ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class AuthorView(ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

# class BookListAPIView(ListAPIView):
#     queryset = Book.objects.all()
#     serializer_class = BookSerializer
#
#
# class BookDetailAPIView(RetrieveAPIView):
#     queryset = Book.objects.all()
#     serializer_class = BookSerializer
#
#
# class AuthorListAPIView(ListAPIView):
#     queryset = Author.objects.all()
#     serializer_class = AuthorSerializer
#
#
# class AuthorDetailAPIView(RetrieveAPIView):
#     queryset = Author.objects.all()
#     serializer_class = AuthorSerializer


def index(request):
    return render(request, 'surf/index.html')


def landingpage(request):
    return render(request, 'surf/landingpage.html')


def login(request):
    return render(request, 'surf/login.html')


def simpleAnimation(request):
    return render(request, 'surf/simple_animation.html')

WRW_Website/WRW_Website/templates/projects_navbar.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">

        {% block header %}
        {% endblock header %}

    </head>
    <body class="img-bg">

        <div class="container-fluid h-100">
            <div class="row">
                <div class="col-sm nopad">
                    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse " id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link myname" href="{% url 'homepage:index' %}">WW</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="{% url 'projects:index' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="{% url 'arcade:index' %}">Arcade</a>
                                        <a class="dropdown-item" href="{% url 'surf:index' %}">Webpages</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>

            {% block body %}
            {% endblock body %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

WRW_Website/arcade/templates/arcade/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>W^2 Projects</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">

        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'arcade/style.css' %}" >

        {% block gameheader %}
        {% endblock gameheader %}

    </head>
    <body class="img-arcade-bg">

        <div class="container-fluid h-100">
            <div class="row">
                <div class="col-sm nopad">
                    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse " id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link myname" href="{% url 'homepage:index' %}">WW</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="{% url 'projects:index' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="{% url 'arcade:index' %}">Arcade</a>
                                        <a class="dropdown-item" href="{% url 'surf:index' %}">Webpages</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>

            {% block body %}
            {% endblock body %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

WRW_Website/arcade/templates/arcade/index.html
{% extends 'projects_navbar.html' %}
{% load staticfiles %}

{% block header %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'arcade/style.css' %}" >
{% endblock header %}

{% block body %}

    <div class="row">
        <div class="col-sm nopad">
            <div class="jumbotron jumbotron-fluid center-txt">
                <h4>More games will be ported to the web July 2018</h4>
            </div>
        </div>
    </div>

    <div class="row h-25 justify-content-center">
        <div class="col-md-4 col-lg-4 mt-4">
            <div class="card">
                <img class="card-img-top" src="{% static 'arcade/images/Phishing.png' %}"  alt="Card image cap">
                <div class="card-block text-center">
                    <h4 class="card-title">Phishing</h4>
                    <p class="card-text">I made this game for a 48 hour game jam. The goal is to catch all the phishing fish while you let all the normal ones through.</p>
                    <a href="{% url 'arcade:phishing' %}" class="btn btn-primary btn-center">Play</a>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

WRW_Website/arcade/templates/arcade/phishing.html
{% extends 'projects_navbar.html' %}
{% load staticfiles %}


{% block header %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'arcade/style.css' %}" >

    <link rel="shortcut icon" href="../../static/arcade/TemplateData/favicon.ico">
    <link rel="stylesheet" href="../../static/arcade/TemplateData/style.css">
    <script src="../../static/arcade/TemplateData/UnityProgress.js"></script>
    <script src="../../static/arcade/Build/UnityLoader.js"></script>
    <script>
        var gameInstance = UnityLoader.instantiate("gameContainer", "../../static/arcade/Build/gamebuilds.json", {onProgress: UnityProgress});
    </script>


{% endblock header %}

{% block body %}
    <div class="webgl-content">
        <div id="gameContainer" style="width: 960px; height: 600px"></div>
        <div class="footer">
            <div class="webgl-logo"></div>
            <div class="fullscreen" onclick="gameInstance.SetFullscreen(1)"></div>
            <div class="title">Fullscreen</div>
        </div>
    </div>
{% endblock body %}

WRW_Website/homepage/templates/homepage/about.html
{% extends 'homepage/base.html' %}
{% load staticfiles %}

{% block header %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" >
{% endblock header %}

{% block body %}

    <div class="row williamimg">
        <div class="col-lg-4 ">
        </div>
        <div class="col-lg-4">
            <h1 class="text-center myname" >William R. Walsh</h1>
        </div>
        <div class="col-lg-4 ">
            <p class="about-text"><br/><br/><br/><br/>Ever since I was a tiny human, I knew that I wanted to be a computer engineer. Before I knew that orange was my favorite color, even before I realized that coffee was my life force, I knew that I loved engineering solutions for all types of situations. In fact, in the third grade we were asked to draw a picture of what we wanted to be when we grew up for a class art project and, while my classmates drew basketballs and ballet slippers, I drew a really poor excuse for a computer. Had I known that my mom would end up purchasing this art project at a charity auction and it would be hanging in our kitchen for everyone to see for all time, I would have tried much harder to make it look more like a computer and less like an old school nintendo controller but what can you do?<br/><br/>After successfully earning a degree in computer engineering, I can honestly say I am doing what I love. With 7+ years of experience in software development, I am proficient in GIS, web development, and several programming languages.<br/><br/>Previously, I worked for the Geography Department at the University of Maryland developing fire detecting algorithms using satellite data. Before that I was an engineer at NASA's Goddard campus managing data for dozens of remote sensing algorithms.<br/><br/>Interested in: web development, game design, and machine learning</p>

        </div>
    </div>

{% endblock body %}

WRW_Website/homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>W^2</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">


        {% block header %}
        {% endblock header %}
    </head>

    <body>
        <div class="container-fluid h-100">
            <div class="row">
                <div class="col-sm nopad">
                    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse " id="navbarSupportedContent">
                            <ul class="navbar-nav mx-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'homepage:about' %}">About Me</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'projects:index' %}">Projects</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
            {% block body %}
            {% endblock body %}
        </div>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

WRW_Website/homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load staticfiles %}

{% block header %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" >
{% endblock header %}

{% block body %}
    <div class="row h-100 bgimg">
        <div class="col-sm h-100 ">
            <h1 class="text-center myname" >William R. Walsh</h1>
        </div>
    </div>
{% endblock body %}

WRW_Website/projects/templates/projects/index.html
{% extends 'projects_navbar.html' %}
{% load staticfiles %}

{% block header %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'projects/style.css' %}" >
{% endblock header %}


{% block body %}

    <!--<div class="row">-->
        <!--<div class="col-sm nopad">-->
            <!--<div class="jumbotron jumbotron-fluid ">-->

            <!--</div>-->
        <!--</div>-->
    <!--</div>-->

    <div class="row h-25">
        <div class="col-md-6 col-lg-4 mt-4">
            <div class="card">
                <img class="card-img-top" src="{% static 'projects/images/Arcade.png' %}" alt="Card image cap">
                <div class="card-block text-center">
                    <h4 class="card-title">2D Video Games</h4>
                    <p class="card-text">Play videos games I've made in my free time.</p>
                    <a href="{% url 'arcade:index' %}" class="btn btn-primary btn-center">Arcade</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 mt-4">
            <div class="card">
                <img class="card-img-top" src="{% static 'projects/images/Web.png' %}" alt="Card image cap">
                <div class="card-block text-center">
                    <h4 class="card-title">Webpages</h4>
                    <p class="card-text">Check out some webpages I've created for practice.</p>
                    <a href="{% url 'surf:index' %}" class="btn btn-primary">Surf</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 mt-4">
            <div class="card">
                <img class="card-img-top " src="{% static 'projects/images/CodeCS.png' %}" alt="Card image cap">
                <div class="card-block text-center ">
                    <h4 class="card-title">Algorithms</h4>
                    <p class="card-text">Take a look at some of my programs and scripts.</p>
                    <a href="#" class="btn btn-secondary">Dive in</a>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

WRW_Website/surf/templates/surf/index.html
{% extends 'projects_navbar.html' %}
{% load staticfiles %}

{% block header %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'surf/css/style.css' %}" >
{% endblock header %}

{% block body %}

    <div class="row">
        <div class="col-sm nopad">
            <div class="jumbotron jumbotron-fluid center-txt">
                <h1>I created these pages purely for practice and experimentation</h1>
                <h4>All these pages are responsive for mobile or tablets</h4>
            </div>
        </div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">Landing Page with Animation</h2>
          <p class="lead">The animation was created with the help the waypoint library.</p>
            <a href="{% url 'surf:simpleAnimation' %}"><div class="anim-img box-shadow mx-auto" style="width: 90%; height: 300px; border-radius: 21px 21px 21px 21px;"></div></a>
        </div>
      </div>
      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <div class="my-3 p-3">
          <h2 class="display-5">Login Page</h2>
            <p class="lead">Icons imported from font awesome.</p>
            <a href="{% url 'surf:login' %}"><div class="login-img box-shadow mx-auto" style="width: 90%; height: 300px; border-radius: 21px 21px 21px 21px;"></div></a>
        </div>
      </div>
    </div>
    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">JSON API</h2>
          <p class="lead">My playground for creating a JSON API - grabbing tables filled with books and authors.</p>
            <a href="./api/"><div class="api-img box-shadow mx-auto" style="width: 90%; height: 300px; border-radius:  21px 21px 21px 21px;"></div></a>
        </div>
      </div>
      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <div class="my-3 p-3">
          <h2 class="display-5">Landing Page</h2>
          <p class="lead">Simple landing page created with only html and css.</p>
             <a href="{% url 'surf:landingpage' %}"><div class="landing-img box-shadow mx-auto" style="width: 90%; height: 300px; border-radius: 21px 21px 21px 21px;"></div></a>
        </div>

      </div>
    </div>

{% endblock body %}

WRW_Website/surf/templates/surf/landingpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'surf/css/style_landingpage.css' %}">
</head>
<body>
    <section class="intro">
        <div class="inner">
            <div class="content">
                <h1>Be Present</h1>
                <a class="btn" href="#">Get Started</a>
            </div>
        </div>
    </section>
    <p class="para"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p class="para"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p class="para"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</body>
</html>

WRW_Website/surf/templates/surf/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Form</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
    <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'surf/css/style_login.css' %}">
</head>
<body>
    <div class="modal-dialog text-center">
        <div class="col-sm-8 main-section">
            <div class="modal-content">
                <div class="col-12 user-img">
                    <img src="{% static 'surf/images/face.png' %}">
                </div>

                <form class="col-12">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Enter Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Enter Password">
                    </div>

                    <button type="submit" class="btn"><i class="fas fa-sign-in-alt"></i>Login</button>
                </form>


                <div class="cold-12 forgot">
                    <a href="#">Forgot Password?</a>
                </div>

            </div> <!-- End of Modal Content -->
        </div>
    </div>
  

</body>
</html>